### ISSUE TITLE
Live.MSpec.Extension

### ISSUE THREAD

**Issue by MASchuer** [dotnetprofessional/ABus#5]
Do you have a nuget for 'LiveSpec.Mspec.Extensionss' hosted anywhere that i can add? 
thanks,
Mark

**Comment by dotnetprofessional** [comment]
Just remove the test project for now. The test project is out of date. I'll update it when I get an in memory transport.

Sent from my Windows Phone

**Comment by marcmihalack** [comment]
Are you working on memory transport?  I already started, should have it
done this weekend.

**Comment by dotnetprofessional** [comment]
I've not started that. I'll be working on the error queue

Sent from my Windows Phone

**Comment by MASchuer** [comment]
Removing the test project worked great.
thanks!
