### ISSUE TITLE
Pipeline.GetTypesImplementingInterface not finding IHostConfigure by default

### ISSUE THREAD

**Issue by MASchuer** [dotnetprofessional/ABus#6]
I'm not sure how you want to manage this, but in order for the ABus.Host to start, it needs to have all of the ABus.Sample Dll's in the Bin directory. 
This seems almost like a hack, but i can add this to the ABus.Sample project post build events.. 
xcopy /Y "$(ProjectDir)$(OutDir)*.dll" "$(SolutionDir)ABus.Host\bin\Debug"

any other ideas that would match were you want this to go?

**Comment by dotnetprofessional** [comment]
This is not necessary. The design calls for you to have the host with your dlls not the other way around. When you install the nuget it will add a reference to the exe to your class project.

To run the sample you start the sample project not the ABus.Host project.

Sent from my Windows Phone

**Comment by dotnetprofessional** [comment]
Closing out issue as this is expected behavior. The host exe needs to reside with the handler dlls so that they can be picked up during startup.
